---
# tasks file for ansible-tower-setup
- name: include vault variables
  include_vars: vault.yml

- name: Set authorized key in main node
  authorized_key:
    user: root
    state: present
    key: "{{ lookup('file', '~/.ssh/automateit_id_rsa.pub') }}"

- name: Set authorized key in cluster nodes
  authorized_key:
    user: root
    state: present
    key: "{{ lookup('file', '~/.ssh/automateit_id_rsa.pub') }}"
  delegate_to: "{{ item }}"
  delegate_facts: true
  loop: "{{ groups['cluster_nodes'] }}"

- name: place dev trust cert
  template:
    src: dev-ansible-tower-trust.crt.j2
    dest: /root/ansible-tower-trust.crt
    mode: '0644'
  when: tower_environment == "dev"

- name: place prod trust cert
  template:
    src: prod-ansible-tower-trust.crt.j2
    dest: /root/ansible-tower-trust.crt
    mode: '0644'
  when: tower_environment == "prod"

- name: place dev tower cert
  template:
    src: dev-tower.cert.j2
    dest: /root/tower.cert
    mode: '0644'
  when: tower_environment == "dev"

- name: place prod tower cert
  template:
    src: prod-tower.cert.j2
    dest: /root/tower.cert
    mode: '0644'
  when: tower_environment == "prod"

- name: place dev tower key
  template:
    src: dev-tower.key.j2
    dest: /root/tower.key
    mode: '0644'
  when: tower_environment == "dev"

- name: place prod tower key
  template:
    src: prod-tower.key.j2
    dest: /root/tower.key
    mode: '0644'
  when: tower_environment == "prod"

- name: place automateit public ssh key
  template:
    src: automateit_id_rsa.pub.j2
    dest: /root/.ssh/id_rsa.pub
    mode: '0400'
    owner: "{{ admin_user }}"

- name: place automateit private ssh key
  template:
    src: automateit_id_rsa.j2
    dest: /root/.ssh/id_rsa
    mode: '0400'
    owner: "{{ admin_user }}"

- name: Create a tower directory
  file:
    path: /etc/tower
    state: directory
    mode: '0755'

- name: place prod db key
  template:
    src: prod-secret-key.j2
    dest: /etc/tower/SECRET_KEY
    mode: '0644'
  when: tower_environment == "prod"